---
abstract: 'Avalara SOAP interface as compiled Perl methods'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::MoreUtils: '0'
  List::Util: '1.33'
  Test::More: '0.94'
  Test::RequiresInternet: '0'
  perl: '5.012'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.032, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Avalara-AvaTax
provides:
  WebService::Avalara::AvaTax:
    file: lib/WebService/Avalara/AvaTax.pm
    version: '0.009'
  WebService::Avalara::AvaTax::Role::Connection:
    file: lib/WebService/Avalara/AvaTax/Role/Connection.pm
    version: '0.009'
  WebService::Avalara::AvaTax::Service::Address:
    file: lib/WebService/Avalara/AvaTax/Service/Address.pm
    version: '0.009'
  WebService::Avalara::AvaTax::Service::Tax:
    file: lib/WebService/Avalara/AvaTax/Service/Tax.pm
    version: '0.009'
requires:
  Carp: '0'
  Const::Fast: '0'
  English: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  LWPx::UserAgent::Cached: '0'
  Log::Report: '0'
  Modern::Perl: '0'
  Moo: '0'
  Moo::Role: '0'
  MooX::Types::MooseLike::Email: '0'
  Mozilla::CA: '0'
  Package::Stash: '0'
  Scalar::Util: '0'
  Sys::Hostname: '0'
  Types::Standard: '0'
  Types::URI: '0'
  URI: '0'
  XML::Compile::SOAP11: '0'
  XML::Compile::SOAP12: '0'
  XML::Compile::SOAP::WSS: '0'
  XML::Compile::Transport::SOAPHTTP: '0'
  XML::Compile::WSDL11: '0'
  XML::Compile::WSS: '0'
  namespace::clean: '0'
  perl: '5.012'
  utf8: '0'
resources:
  bugtracker: https://github.com/mjgardner/WebService-Avalara-AvaTax/issues
  homepage: http://metacpan.org/release/WebService-Avalara-AvaTax/
  repository: git://github.com/mjgardner/WebService-Avalara-AvaTax.git
version: '0.009'
